name: Resourcepack Zipper

permissions:
  contents: write
  
on:
  push:
    branches:
      - master  # Adjust this branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # A non-shallow repository clone is required

    - name: Run PackSquash
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        packsquash_version: latest
        shader_source_transformation_strategy: keep_as_is

    - name: Create ZIP file
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        ZIP_NAME="RP.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r "${ZIP_NAME}" .

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: resource-pack-artifact
        path: ${{ env.ZIP_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/${{ env.ZIP_NAME }}
        asset_name: ${{ env.ZIP_NAME }}
        asset_content_type: application/zip

    - name: Checkout pack-dist branch
      uses: actions/checkout@v2
      with:
        ref: pack-dist
        path: pack-dist

    - name: Copy ZIP to pack-dist
      run: |
        cp "${{ env.ZIP_NAME }}" pack-dist/RP.zip

    - name: Commit and push to pack-dist
      run: |
        cd pack-dist
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add RP.zip
        git commit -m "Update RP.zip from ${{ github.sha }}" || echo "No changes to commit"
        git push origin pack-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
